Traceback (most recent call last):
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'labels'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 323, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 318, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 42, in train
    train_instances = os.path.join(config.labels, 'train_instances_fixed_frange_bboxes_len.json')
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'labels'
Traceback (most recent call last):
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'labels'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 323, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 318, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 42, in train
    train_instances = os.path.join(config.labels, 'train_instances_fixed_frange_bboxes_len.json')
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'labels'
